// ================= TOP 500 CUVINTE ENGLEZE =================
// Cele mai frecvente/utile 500 de cuvinte din engleza, pentru un incepator.
// Fiecare are: en = cuvantul, fon = pronuntia pe romaneste, ro = traducerea.
// Pronuntia e o aproximare prietenoasa (a = sunetul neutru).

export const VOCABULAR_500 = [
  { en: "the", fon: "dă", ro: "articolul hotărât (cel, cea)" },
  { en: "be", fon: "bii", ro: "a fi" },
  { en: "to", fon: "tu", ro: "la, către, spre" },
  { en: "of", fon: "ăv", ro: "al, ai, din" },
  { en: "and", fon: "end", ro: "și" },
  { en: "a", fon: "ă / ei", ro: "un, o" },
  { en: "in", fon: "in", ro: "în" },
  { en: "that", fon: "det", ro: "acela, că" },
  { en: "have", fon: "hev", ro: "a avea" },
  { en: "I", fon: "ai", ro: "eu" },
  { en: "it", fon: "it", ro: "el/ea (lucru), asta" },
  { en: "for", fon: "for", ro: "pentru" },
  { en: "not", fon: "not", ro: "nu (negație)" },
  { en: "on", fon: "on", ro: "pe" },
  { en: "with", fon: "uidh", ro: "cu" },
  { en: "he", fon: "hi", ro: "el" },
  { en: "as", fon: "ez", ro: "ca, precum, în timp ce" },
  { en: "you", fon: "iu", ro: "tu, voi, dumneavoastră" },
  { en: "do", fon: "du", ro: "a face" },
  { en: "at", fon: "et", ro: "la, în (loc/timp)" },
  { en: "this", fon: "dhis", ro: "acesta, aceasta" },
  { en: "but", fon: "bat", ro: "dar" },
  { en: "his", fon: "hiz", ro: "al lui" },
  { en: "by", fon: "bai", ro: "de către, lângă" },
  { en: "from", fon: "from", ro: "de la, din" },
  { en: "they", fon: "dhei", ro: "ei, ele" },
  { en: "we", fon: "ui", ro: "noi" },
  { en: "say", fon: "sei", ro: "a spune, a zice" },
  { en: "her", fon: "hăr", ro: "ei, pe ea, al ei" },
  { en: "she", fon: "și", ro: "ea" },
  { en: "or", fon: "or", ro: "sau, ori" },
  { en: "an", fon: "en", ro: "un, o (înainte de vocală)" },
  { en: "will", fon: "uil", ro: "va (viitor); voință" },
  { en: "my", fon: "mai", ro: "al meu, a mea" },
  { en: "one", fon: "uan", ro: "unu, unul" },
  { en: "all", fon: "ol", ro: "tot, toți, toate" },
  { en: "would", fon: "uud", ro: "ar (condițional)" },
  { en: "there", fon: "dher", ro: "acolo" },
  { en: "their", fon: "dher", ro: "al lor" },
  { en: "what", fon: "uot", ro: "ce" },
  { en: "so", fon: "sou", ro: "așa, deci, atât de" },
  { en: "up", fon: "ap", ro: "sus, în sus" },
  { en: "out", fon: "aut", ro: "afară" },
  { en: "if", fon: "if", ro: "dacă" },
  { en: "about", fon: "ăbaut", ro: "despre, aproximativ" },
  { en: "who", fon: "hu", ro: "cine, care" },
  { en: "get", fon: "get", ro: "a obține, a primi, a ajunge" },
  { en: "which", fon: "uici", ro: "care" },
  { en: "go", fon: "gou", ro: "a merge, a se duce" },
  { en: "me", fon: "mi", ro: "pe mine, mie" },
  { en: "when", fon: "uen", ro: "când" },
  { en: "make", fon: "meic", ro: "a face, a crea" },
  { en: "can", fon: "chen", ro: "a putea; conservă" },
  { en: "like", fon: "laic", ro: "a plăcea; ca, asemenea" },
  { en: "time", fon: "taim", ro: "timp, oră, dată" },
  { en: "no", fon: "nou", ro: "nu; niciun" },
  { en: "just", fon: "giast", ro: "doar, tocmai; corect" },
  { en: "him", fon: "him", ro: "pe el, lui" },
  { en: "know", fon: "nou", ro: "a ști, a cunoaște" },
  { en: "take", fon: "teic", ro: "a lua, a duce" },
  { en: "people", fon: "pipăl", ro: "oameni, lume" },
  { en: "into", fon: "intu", ro: "în (spre interior)" },
  { en: "year", fon: "iir", ro: "an" },
  { en: "your", fon: "ior", ro: "al tău, al vostru" },
  { en: "good", fon: "gud", ro: "bun, bine" },
  { en: "some", fon: "sam", ro: "niște, câțiva" },
  { en: "could", fon: "cud", ro: "ar putea, putea (trecut)" },
  { en: "them", fon: "dhem", ro: "pe ei, pe ele, lor" },
  { en: "see", fon: "sii", ro: "a vedea" },
  { en: "other", fon: "adhăr", ro: "altul, celălalt" },
  { en: "than", fon: "dhen", ro: "decât" },
  { en: "then", fon: "dhen", ro: "atunci, apoi" },
  { en: "now", fon: "nau", ro: "acum" },
  { en: "look", fon: "luc", ro: "a se uita, a privi; privire" },
  { en: "only", fon: "óunli", ro: "doar, numai" },
  { en: "come", fon: "cam", ro: "a veni" },
  { en: "its", fon: "its", ro: "al său (pentru lucruri)" },
  { en: "over", fon: "óuvăr", ro: "peste, deasupra; gata" },
  { en: "think", fon: "think", ro: "a gândi, a crede" },
  { en: "also", fon: "ólsou", ro: "de asemenea, și" },
  { en: "back", fon: "bec", ro: "înapoi; spate" },
  { en: "after", fon: "áftăr", ro: "după" },
  { en: "use", fon: "iuz", ro: "a folosi; utilizare" },
  { en: "two", fon: "tu", ro: "doi, două" },
  { en: "how", fon: "hau", ro: "cum" },
  { en: "our", fon: "aur", ro: "al nostru" },
  { en: "work", fon: "uărc", ro: "a lucra; muncă, lucru" },
  { en: "first", fon: "fărst", ro: "primul, întâi" },
  { en: "well", fon: "uel", ro: "bine; fântână" },
  { en: "way", fon: "uei", ro: "cale, drum, fel" },
  { en: "even", fon: "íivăn", ro: "chiar, până și; par (număr)" },
  { en: "new", fon: "niu", ro: "nou" },
  { en: "want", fon: "uont", ro: "a vrea, a dori" },
  { en: "because", fon: "bicóz", ro: "pentru că, fiindcă" },
  { en: "any", fon: "éni", ro: "vreun, oricare" },
  { en: "these", fon: "dhiiz", ro: "aceștia, acestea" },
  { en: "give", fon: "ghiv", ro: "a da, a oferi" },
  { en: "day", fon: "dei", ro: "zi" },
  { en: "most", fon: "moust", ro: "cel mai (mult), majoritatea" },
  { en: "us", fon: "as", ro: "pe noi, nouă" },
  { en: "man", fon: "men", ro: "bărbat, om" },
  { en: "find", fon: "faind", ro: "a găsi" },
  { en: "here", fon: "hiir", ro: "aici" },
  { en: "thing", fon: "thing", ro: "lucru" },
  { en: "tell", fon: "tel", ro: "a spune, a povesti" },
  { en: "very", fon: "véri", ro: "foarte" },
  { en: "need", fon: "niid", ro: "a avea nevoie; nevoie" },
  { en: "feel", fon: "fiil", ro: "a simți" },
  { en: "high", fon: "hai", ro: "înalt, ridicat" },
  { en: "too", fon: "tu", ro: "prea; de asemenea" },
  { en: "place", fon: "pleis", ro: "loc; a pune" },
  { en: "little", fon: "lítăl", ro: "mic, puțin" },
  { en: "world", fon: "uărld", ro: "lume" },
  { en: "still", fon: "stil", ro: "încă; liniștit" },
  { en: "school", fon: "scuul", ro: "școală" },
  { en: "family", fon: "fémili", ro: "familie" },
  { en: "off", fon: "of", ro: "oprit; de pe, departe" },
  { en: "child", fon: "ciaild", ro: "copil" },
  { en: "few", fon: "fiu", ro: "puțini, câțiva" },
  { en: "while", fon: "uail", ro: "în timp ce; o vreme" },
  { en: "last", fon: "last", ro: "ultimul; a dura" },
  { en: "own", fon: "óun", ro: "propriu; a deține" },
  { en: "under", fon: "andăr", ro: "sub, dedesubt" },
  { en: "read", fon: "riid", ro: "a citi" },
  { en: "keep", fon: "chiip", ro: "a păstra, a ține" },
  { en: "student", fon: "stiúdănt", ro: "student, elev" },
  { en: "big", fon: "big", ro: "mare" },
  { en: "every", fon: "évri", ro: "fiecare" },
  { en: "another", fon: "ănadhăr", ro: "un altul, încă unul" },
  { en: "much", fon: "maci", ro: "mult" },
  { en: "such", fon: "saci", ro: "așa, atât de" },
  { en: "through", fon: "thru", ro: "prin, printre" },
  { en: "where", fon: "uer", ro: "unde" },
  { en: "same", fon: "seim", ro: "același, la fel" },
  { en: "hand", fon: "hend", ro: "mână" },
  { en: "eye", fon: "ai", ro: "ochi" },
  { en: "part", fon: "part", ro: "parte" },
  { en: "again", fon: "ăghén", ro: "din nou, iar" },
  { en: "help", fon: "help", ro: "a ajuta; ajutor" },
  { en: "put", fon: "put", ro: "a pune" },
  { en: "days", fon: "deiz", ro: "zile" },
  { en: "different", fon: "dífrănt", ro: "diferit" },
  { en: "away", fon: "ăuéi", ro: "departe, plecat" },
  { en: "turn", fon: "tărn", ro: "a (se) întoarce; rând, tură" },
  { en: "move", fon: "muuv", ro: "a (se) mișca, a muta" },
  { en: "old", fon: "óuld", ro: "bătrân, vechi" },
  { en: "life", fon: "laif", ro: "viață" },
  { en: "woman", fon: "úumăn", ro: "femeie" },
  { en: "home", fon: "houm", ro: "casă, acasă" },
  { en: "many", fon: "méni", ro: "mulți, multe" },
  { en: "those", fon: "dhóuz", ro: "aceia, acelea" },
  { en: "small", fon: "smol", ro: "mic" },
  { en: "large", fon: "largi", ro: "mare, larg" },
  { en: "next", fon: "necst", ro: "următorul, lângă" },
  { en: "early", fon: "árli", ro: "devreme" },
  { en: "young", fon: "iang", ro: "tânăr" },
  { en: "important", fon: "impórtănt", ro: "important" },
  { en: "bad", fon: "bed", ro: "rău" },
  { en: "call", fon: "col", ro: "a suna, a chema; apel" },
  { en: "week", fon: "uiic", ro: "săptămână" },
  { en: "night", fon: "nait", ro: "noapte" },
  { en: "today", fon: "tudéi", ro: "azi, astăzi" },
  { en: "bring", fon: "bring", ro: "a aduce" },
  { en: "happen", fon: "hépăn", ro: "a se întâmpla" },
  { en: "without", fon: "uidháut", ro: "fără" },
  { en: "before", fon: "bifór", ro: "înainte de" },
  { en: "must", fon: "mast", ro: "a trebui (obligatoriu)" },
  { en: "water", fon: "uótăr", ro: "apă" },
  { en: "room", fon: "ruum", ro: "cameră; spațiu" },
  { en: "mother", fon: "madhăr", ro: "mamă" },
  { en: "money", fon: "máni", ro: "bani" },
  { en: "month", fon: "manth", ro: "lună (calendar)" },
  { en: "lot", fon: "lot", ro: "mult, o grămadă" },
  { en: "right", fon: "rait", ro: "corect; dreapta; drept" },
  { en: "study", fon: "stádi", ro: "a studia; studiu" },
  { en: "book", fon: "buc", ro: "carte; a rezerva" },
  { en: "word", fon: "uărd", ro: "cuvânt" },
  { en: "kind", fon: "caind", ro: "fel, tip; blând" },
  { en: "four", fon: "for", ro: "patru" },
  { en: "head", fon: "hed", ro: "cap; a conduce" },
  { en: "far", fon: "far", ro: "departe" },
  { en: "black", fon: "blec", ro: "negru" },
  { en: "long", fon: "long", ro: "lung; mult timp" },
  { en: "both", fon: "bouth", ro: "amândoi, ambii" },
  { en: "house", fon: "haus", ro: "casă" },
  { en: "yes", fon: "ies", ro: "da" },
  { en: "since", fon: "sins", ro: "de când, deoarece" },
  { en: "around", fon: "ăraund", ro: "în jur, în jurul" },
  { en: "friend", fon: "frend", ro: "prieten" },
  { en: "father", fon: "fadhăr", ro: "tată" },
  { en: "sit", fon: "sit", ro: "a (se) așeza, a sta jos" },
  { en: "until", fon: "ăntíl", ro: "până când" },
  { en: "hour", fon: "aur", ro: "oră (60 min)" },
  { en: "game", fon: "gheim", ro: "joc" },
  { en: "often", fon: "ófăn", ro: "des, adesea" },
  { en: "yet", fon: "iet", ro: "încă; totuși" },
  { en: "end", fon: "end", ro: "sfârșit; a termina" },
  { en: "stand", fon: "stend", ro: "a sta în picioare, a suporta" },
  { en: "lose", fon: "luuz", ro: "a pierde" },
  { en: "pay", fon: "pei", ro: "a plăti; plată" },
  { en: "law", fon: "lo", ro: "lege" },
  { en: "meet", fon: "miit", ro: "a (se) întâlni, a cunoaște" },
  { en: "car", fon: "car", ro: "mașină" },
  { en: "city", fon: "síti", ro: "oraș" },
  { en: "almost", fon: "ólmoust", ro: "aproape" },
  { en: "name", fon: "neim", ro: "nume; a numi" },
  { en: "five", fon: "faiv", ro: "cinci" },
  { en: "once", fon: "uans", ro: "o dată; odată" },
  { en: "white", fon: "uait", ro: "alb" },
  { en: "learn", fon: "lărn", ro: "a învăța" },
  { en: "change", fon: "ceingi", ro: "a schimba; schimbare, rest" },
  { en: "minute", fon: "mínit", ro: "minut" },
  { en: "best", fon: "best", ro: "cel mai bun" },
  { en: "idea", fon: "aidíă", ro: "idee" },
  { en: "kid", fon: "chid", ro: "copil, puști" },
  { en: "body", fon: "bódi", ro: "corp, trup" },
  { en: "nothing", fon: "nathing", ro: "nimic" },
  { en: "understand", fon: "andărsténd", ro: "a înțelege" },
  { en: "watch", fon: "uoci", ro: "a urmări; ceas" },
  { en: "together", fon: "tugédhăr", ro: "împreună" },
  { en: "parent", fon: "péerănt", ro: "părinte" },
  { en: "stop", fon: "stop", ro: "a (se) opri; stație" },
  { en: "face", fon: "feis", ro: "față; a înfrunta" },
  { en: "anything", fon: "énithing", ro: "orice, ceva" },
  { en: "already", fon: "olrédi", ro: "deja" },
  { en: "speak", fon: "spiic", ro: "a vorbi" },
  { en: "door", fon: "dor", ro: "ușă" },
  { en: "health", fon: "helth", ro: "sănătate" },
  { en: "person", fon: "pársăn", ro: "persoană" },
  { en: "grow", fon: "grou", ro: "a crește, a cultiva" },
  { en: "open", fon: "óupăn", ro: "a deschide; deschis" },
  { en: "morning", fon: "mórning", ro: "dimineață" },
  { en: "walk", fon: "uoc", ro: "a merge pe jos; plimbare" },
  { en: "low", fon: "lou", ro: "jos, scăzut" },
  { en: "win", fon: "uin", ro: "a câștiga" },
  { en: "girl", fon: "gărl", ro: "fată" },
  { en: "food", fon: "fuud", ro: "mâncare" },
  { en: "himself", fon: "himsélf", ro: "el însuși, pe sine" },
  { en: "air", fon: "eăr", ro: "aer" },
  { en: "teacher", fon: "tíiciăr", ro: "profesor" },
  { en: "enough", fon: "inaf", ro: "destul, suficient" },
  { en: "remember", fon: "rimémbăr", ro: "a-și aminti" },
  { en: "foot", fon: "fut", ro: "picior (laba); ~30 cm" },
  { en: "second", fon: "sécănd", ro: "al doilea; secundă" },
  { en: "boy", fon: "boi", ro: "băiat" },
  { en: "maybe", fon: "méibi", ro: "poate" },
  { en: "toward", fon: "tuórd", ro: "spre, către" },
  { en: "everything", fon: "évrithing", ro: "totul, tot" },
  { en: "love", fon: "lav", ro: "a iubi; dragoste" },
  { en: "music", fon: "miúzic", ro: "muzică" },
  { en: "actually", fon: "écciuăli", ro: "de fapt" },
  { en: "buy", fon: "bai", ro: "a cumpăra" },
  { en: "probably", fon: "próbăbli", ro: "probabil" },
  { en: "wait", fon: "ueit", ro: "a aștepta" },
  { en: "die", fon: "dai", ro: "a muri" },
  { en: "send", fon: "send", ro: "a trimite" },
  { en: "build", fon: "bild", ro: "a construi" },
  { en: "stay", fon: "stei", ro: "a rămâne, a sta" },
  { en: "fall", fon: "fol", ro: "a cădea; toamnă" },
  { en: "oh", fon: "óu", ro: "oh, a (exclamație)" },
  { en: "cut", fon: "cat", ro: "a tăia; tăietură" },
  { en: "someone", fon: "sámuan", ro: "cineva" },
  { en: "behind", fon: "bihaind", ro: "în spatele, în urmă" },
  { en: "six", fon: "sics", ro: "șase" },
  { en: "yeah", fon: "iea", ro: "da (informal)" },
  { en: "care", fon: "cheăr", ro: "a-i păsa; grijă" },
  { en: "late", fon: "leit", ro: "târziu; întârziat" },
  { en: "sell", fon: "sel", ro: "a vinde" },
  { en: "sometimes", fon: "sámtaimz", ro: "uneori, câteodată" },
  { en: "better", fon: "bétăr", ro: "mai bun, mai bine" },
  { en: "decide", fon: "disáid", ro: "a decide, a hotărî" },
  { en: "strong", fon: "strong", ro: "puternic, tare" },
  { en: "heart", fon: "hart", ro: "inimă" },
  { en: "show", fon: "șou", ro: "a arăta; spectacol" },
  { en: "light", fon: "lait", ro: "lumină; ușor; a aprinde" },
  { en: "voice", fon: "vois", ro: "voce" },
  { en: "wife", fon: "uaif", ro: "soție" },
  { en: "police", fon: "pălíis", ro: "poliție" },
  { en: "free", fon: "frii", ro: "liber; gratis" },
  { en: "price", fon: "prais", ro: "preț" },
  { en: "less", fon: "les", ro: "mai puțin" },
  { en: "explain", fon: "ecspléin", ro: "a explica" },
  { en: "son", fon: "san", ro: "fiu" },
  { en: "hope", fon: "houp", ro: "a spera; speranță" },
  { en: "carry", fon: "chéri", ro: "a căra, a duce" },
  { en: "town", fon: "taun", ro: "oraș (mic), târg" },
  { en: "road", fon: "roud", ro: "drum, șosea" },
  { en: "drive", fon: "draiv", ro: "a conduce (mașina)" },
  { en: "arm", fon: "arm", ro: "braț" },
  { en: "true", fon: "tru", ro: "adevărat" },
  { en: "break", fon: "breic", ro: "a sparge, a rupe; pauză" },
  { en: "thank", fon: "thenc", ro: "a mulțumi" },
  { en: "building", fon: "bílding", ro: "clădire" },
  { en: "full", fon: "ful", ro: "plin" },
  { en: "agree", fon: "ăgríi", ro: "a fi de acord" },
  { en: "paper", fon: "péipăr", ro: "hârtie; ziar; lucrare" },
  { en: "everyone", fon: "évriuan", ro: "toată lumea, fiecare" },
  { en: "center", fon: "séntăr", ro: "centru" },
  { en: "table", fon: "téibăl", ro: "masă; tabel" },
  { en: "eat", fon: "iit", ro: "a mânca" },
  { en: "teach", fon: "tiici", ro: "a preda, a învăța pe cineva" },
  { en: "half", fon: "haf", ro: "jumătate" },
  { en: "easy", fon: "íizi", ro: "ușor, simplu" },
  { en: "cost", fon: "cost", ro: "a costa; cost" },
  { en: "street", fon: "striit", ro: "stradă" },
  { en: "itself", fon: "itsélf", ro: "el/ea însuși (lucru)" },
  { en: "phone", fon: "foun", ro: "telefon" },
  { en: "either", fon: "áidhăr", ro: "oricare (din doi); nici" },
  { en: "picture", fon: "píciăr", ro: "poză, imagine" },
  { en: "describe", fon: "discráib", ro: "a descrie" },
  { en: "wall", fon: "uol", ro: "perete, zid" },
  { en: "baby", fon: "béibi", ro: "bebeluș, copil mic" },
  { en: "computer", fon: "cămpiútăr", ro: "calculator" },
  { en: "type", fon: "taip", ro: "tip, fel; a tasta" },
  { en: "hot", fon: "hot", ro: "fierbinte, cald" },
  { en: "cold", fon: "could", ro: "rece; răceală" },
  { en: "ready", fon: "rédi", ro: "gata, pregătit" },
  { en: "sound", fon: "saund", ro: "sunet; a suna" },
  { en: "job", fon: "giob", ro: "slujbă, loc de muncă" },
  { en: "sport", fon: "sport", ro: "sport" },
  { en: "fast", fon: "fast", ro: "rapid, repede" },
  { en: "yesterday", fon: "iéstărdei", ro: "ieri" },
  { en: "tomorrow", fon: "tumórou", ro: "mâine" },
  { en: "close", fon: "clouz", ro: "a închide; aproape" },
  { en: "hold", fon: "hould", ro: "a ține" },
  { en: "travel", fon: "trévăl", ro: "a călători; călătorie" },
  { en: "beautiful", fon: "biútifăl", ro: "frumos" },
  { en: "happy", fon: "hépi", ro: "fericit, bucuros" },
  { en: "sad", fon: "sed", ro: "trist" },
  { en: "tired", fon: "táiărd", ro: "obosit" },
  { en: "hungry", fon: "hángri", ro: "flămând, înfometat" },
  { en: "sleep", fon: "sliip", ro: "a dormi; somn" },
  { en: "wake", fon: "ueic", ro: "a (se) trezi" },
  { en: "run", fon: "ran", ro: "a alerga, a rula" },
  { en: "jump", fon: "giamp", ro: "a sări" },
  { en: "smile", fon: "smail", ro: "a zâmbi; zâmbet" },
  { en: "laugh", fon: "laf", ro: "a râde" },
  { en: "cry", fon: "crai", ro: "a plânge; strigăt" },
  { en: "sing", fon: "sing", ro: "a cânta (cu vocea)" },
  { en: "dance", fon: "dans", ro: "a dansa; dans" },
  { en: "play", fon: "plei", ro: "a (se) juca, a cânta la" },
  { en: "cook", fon: "cuc", ro: "a găti; bucătar" },
  { en: "clean", fon: "cliin", ro: "a curăța; curat" },
  { en: "wash", fon: "uoș", ro: "a spăla" },
  { en: "evening", fon: "íivning", ro: "seară" },
  { en: "weekend", fon: "uícend", ro: "weekend, sfârșit de săptămână" },
  { en: "birthday", fon: "bărthdei", ro: "zi de naștere" },
  { en: "holiday", fon: "hólidei", ro: "vacanță; sărbătoare" },
  { en: "weather", fon: "uédhăr", ro: "vreme" },
  { en: "rain", fon: "rein", ro: "ploaie; a ploua" },
  { en: "snow", fon: "snou", ro: "zăpadă; a ninge" },
  { en: "sun", fon: "san", ro: "soare" },
  { en: "wind", fon: "uind", ro: "vânt" },
  { en: "warm", fon: "uorm", ro: "cald" },
  { en: "color", fon: "cálăr", ro: "culoare" },
  { en: "red", fon: "red", ro: "roșu" },
  { en: "blue", fon: "blu", ro: "albastru" },
  { en: "green", fon: "griin", ro: "verde" },
  { en: "yellow", fon: "iélou", ro: "galben" },
  { en: "number", fon: "námbăr", ro: "număr" },
  { en: "three", fon: "thrii", ro: "trei" },
  { en: "seven", fon: "sévăn", ro: "șapte" },
  { en: "eight", fon: "eit", ro: "opt" },
  { en: "nine", fon: "nain", ro: "nouă (9)" },
  { en: "ten", fon: "ten", ro: "zece" },
  { en: "hundred", fon: "hándrăd", ro: "sută" },
  { en: "thousand", fon: "tháuzănd", ro: "mie (1000)" },
  { en: "shop", fon: "șop", ro: "magazin; a face cumpărături" },
  { en: "store", fon: "stor", ro: "magazin; a depozita" },
  { en: "bread", fon: "bred", ro: "pâine" },
  { en: "milk", fon: "milc", ro: "lapte" },
  { en: "coffee", fon: "cófi", ro: "cafea" },
  { en: "tea", fon: "tii", ro: "ceai" },
  { en: "apple", fon: "épăl", ro: "măr" },
  { en: "fruit", fon: "frut", ro: "fruct" },
  { en: "meat", fon: "miit", ro: "carne" },
  { en: "egg", fon: "eg", ro: "ou" },
  { en: "fish", fon: "fiș", ro: "pește" },
  { en: "dog", fon: "dog", ro: "câine" },
  { en: "cat", fon: "chet", ro: "pisică" },
  { en: "bird", fon: "bărd", ro: "pasăre" },
  { en: "tree", fon: "trii", ro: "copac" },
  { en: "flower", fon: "fláuăr", ro: "floare" },
  { en: "garden", fon: "gárdăn", ro: "grădină" },
  { en: "kitchen", fon: "chíciăn", ro: "bucătărie" },
  { en: "bed", fon: "bed", ro: "pat" },
  { en: "chair", fon: "cheăr", ro: "scaun" },
  { en: "window", fon: "uíndou", ro: "fereastră" },
  { en: "floor", fon: "flor", ro: "podea; etaj" },
  { en: "key", fon: "chii", ro: "cheie; tastă" },
  { en: "bag", fon: "beg", ro: "geantă, pungă" },
  { en: "clothes", fon: "clouz", ro: "haine" },
  { en: "shoe", fon: "șu", ro: "pantof" },
  { en: "shirt", fon: "șărt", ro: "cămașă, tricou" },
  { en: "train", fon: "trein", ro: "tren; a antrena" },
  { en: "bus", fon: "bas", ro: "autobuz" },
  { en: "plane", fon: "plein", ro: "avion" },
  { en: "ticket", fon: "tíchet", ro: "bilet" },
  { en: "airport", fon: "éerport", ro: "aeroport" },
  { en: "hospital", fon: "hóspităl", ro: "spital" },
  { en: "medicine", fon: "médisin", ro: "medicament; medicină" },
  { en: "pain", fon: "pein", ro: "durere" },
  { en: "sick", fon: "sic", ro: "bolnav" },
  { en: "problem", fon: "próblăm", ro: "problemă" },
  { en: "question", fon: "cuésciăn", ro: "întrebare" },
  { en: "answer", fon: "ánsăr", ro: "răspuns; a răspunde" },
  { en: "please", fon: "pliiz", ro: "te rog, vă rog" },
  { en: "sorry", fon: "sóri", ro: "îmi pare rău, scuze" },
  { en: "welcome", fon: "uélcăm", ro: "bine ai venit; cu plăcere" },
  { en: "hello", fon: "helóu", ro: "bună, salut" },
  { en: "goodbye", fon: "gudbái", ro: "la revedere" },
  { en: "language", fon: "léngueg", ro: "limbă (vorbită)" },
  { en: "English", fon: "ínglișă", ro: "engleză" },
  { en: "letter", fon: "létăr", ro: "literă; scrisoare" },
  { en: "write", fon: "rait", ro: "a scrie" },
  { en: "listen", fon: "lísăn", ro: "a asculta" },
  { en: "forget", fon: "fărghét", ro: "a uita" },
  { en: "always", fon: "ólueiz", ro: "întotdeauna, mereu" },
  { en: "never", fon: "névăr", ro: "niciodată" },
  { en: "usually", fon: "iújuăli", ro: "de obicei" },
  { en: "soon", fon: "suun", ro: "curând, în curând" },
  { en: "slow", fon: "slou", ro: "încet, lent" },
  { en: "difficult", fon: "díficălt", ro: "dificil, greu" },
  { en: "nice", fon: "nais", ro: "drăguț, plăcut" },
  { en: "wrong", fon: "rong", ro: "greșit, nepotrivit" },
  { en: "start", fon: "start", ro: "a începe; început" },
  { en: "finish", fon: "fíniș", ro: "a termina, a finaliza" },
  { en: "begin", fon: "bighín", ro: "a începe" },
  { en: "try", fon: "trai", ro: "a încerca" },
  { en: "believe", fon: "bilíiv", ro: "a crede (în ceva)" },
  { en: "hear", fon: "hiir", ro: "a auzi" },
  { en: "leave", fon: "liiv", ro: "a pleca; a lăsa" },
  { en: "arrive", fon: "ăráiv", ro: "a sosi, a ajunge" },
  { en: "enter", fon: "éntăr", ro: "a intra" },
  { en: "ask", fon: "asc", ro: "a întreba, a cere" },
  { en: "fix", fon: "fics", ro: "a repara, a fixa" },
  { en: "fly", fon: "flai", ro: "a zbura; muscă" },
  { en: "swim", fon: "suim", ro: "a înota" },
  { en: "drink", fon: "drinc", ro: "a bea; băutură" },
  { en: "live", fon: "liv", ro: "a trăi, a locui" },
  { en: "become", fon: "bicám", ro: "a deveni" },
  { en: "seem", fon: "siim", ro: "a părea" },
  { en: "mean", fon: "miin", ro: "a însemna; rău, meschin" },
  { en: "wish", fon: "uiș", ro: "a-și dori, a ura; dorință" },
  { en: "enjoy", fon: "ingiói", ro: "a se bucura de, a savura" },
  { en: "choose", fon: "ciuuz", ro: "a alege" },
  { en: "promise", fon: "prómis", ro: "a promite; promisiune" },
  { en: "worry", fon: "uári", ro: "a-și face griji; grijă" },
  { en: "afraid", fon: "ăfréid", ro: "speriat, temător" },
  { en: "angry", fon: "éngri", ro: "supărat, furios" },
  { en: "surprise", fon: "sărpráiz", ro: "surpriză; a surprinde" },
  { en: "interesting", fon: "íntrăsting", ro: "interesant" },
  { en: "boring", fon: "bóring", ro: "plictisitor" },
  { en: "funny", fon: "fáni", ro: "amuzant, haios" },
  { en: "strange", fon: "streingi", ro: "ciudat, straniu" },
  { en: "dangerous", fon: "déingerăs", ro: "periculos" },
  { en: "safe", fon: "seif", ro: "sigur, în siguranță" },
  { en: "careful", fon: "chéerfăl", ro: "atent, grijuliu" },
  { en: "quick", fon: "cuic", ro: "rapid, iute" },
  { en: "quiet", fon: "cuáiăt", ro: "liniștit, tăcut" },
  { en: "loud", fon: "laud", ro: "zgomotos, tare" },
  { en: "dirty", fon: "dárti", ro: "murdar" },
  { en: "empty", fon: "émti", ro: "gol, liber" },
  { en: "heavy", fon: "hévi", ro: "greu (la cântar)" },
  { en: "weak", fon: "uiic", ro: "slab, firav" },
  { en: "rich", fon: "rici", ro: "bogat" },
  { en: "poor", fon: "puur", ro: "sărac; biet" },
  { en: "short", fon: "șort", ro: "scurt, scund" },
  { en: "wide", fon: "uaid", ro: "lat, larg" },
  { en: "narrow", fon: "nérou", ro: "îngust, strâmt" },
  { en: "deep", fon: "diip", ro: "adânc; profund" },
  { en: "thick", fon: "thic", ro: "gros, des" },
  { en: "thin", fon: "thin", ro: "subțire; slab" },
  { en: "near", fon: "niir", ro: "aproape, apropiat" },
  { en: "left", fon: "left", ro: "stânga; rămas" },
  { en: "front", fon: "front", ro: "față, parte din față" },
  { en: "top", fon: "top", ro: "vârf, partea de sus" },
  { en: "bottom", fon: "bótăm", ro: "fund, partea de jos" },
  { en: "middle", fon: "mídăl", ro: "mijloc, centru" },
  { en: "inside", fon: "insáid", ro: "înăuntru, interior" },
  { en: "outside", fon: "autsáid", ro: "afară, exterior" },
  { en: "between", fon: "bituíin", ro: "între" },
  { en: "next to", fon: "necst tu", ro: "lângă, alături de" },
  { en: "against", fon: "ăghénst", ro: "împotriva, contra" },
  { en: "during", fon: "diúring", ro: "în timpul" },
  { en: "rarely", fon: "réerli", ro: "rar, arareori" },
  { en: "alone", fon: "ălóun", ro: "singur" },
  { en: "really", fon: "ríili", ro: "chiar, cu adevărat" },
  { en: "something", fon: "sámthing", ro: "ceva" },
  { en: "anyone", fon: "éniuan", ro: "oricine" },
  { en: "nobody", fon: "nóubădi", ro: "nimeni" },
  { en: "everywhere", fon: "évriuer", ro: "peste tot" },
  { en: "somewhere", fon: "sámuer", ro: "undeva" },
  { en: "anywhere", fon: "éniuer", ro: "oriunde" },
  { en: "nowhere", fon: "nóuuer", ro: "nicăieri" },
  { en: "congratulations", fon: "cangreciuléișănz", ro: "felicitări" },
  { en: "good luck", fon: "gud lac", ro: "mult noroc, baftă" },
  { en: "of course", fon: "ăv cors", ro: "desigur, bineînțeles" },
  { en: "excuse me", fon: "ecschiúz mi", ro: "scuză-mă, permiteți" },
  { en: "you're welcome", fon: "iur uélcăm", ro: "cu plăcere" },
];

export default VOCABULAR_500;
